feat: Improve Vagrantfile decoupling env variables

diff --git a/vagrant/Vagrantfile b/vagrant/Vagrantfile
--- a/vagrant/Vagrantfile
+++ b/vagrant/Vagrantfile
@@ -4,33 +4,32 @@
 require 'pathname'
 require 'fileutils'
 
-# Method to load environment variables from an .env file
+# Method to load environment variables from an .env file and return them as a hash
 def load_env(file)
+  env_vars = {}
   if File.exist?(file)
     File.readlines(file).each do |line|
       key, value = line.strip.split('=', 2)
-      ENV[key] = value if key && value
+      if key && value
+        ENV[key] = value
+        env_vars[key] = value
+      end
     end
   else
     raise "Env file not found: #{file}"
   end
+  env_vars
 end
 
-# Load .env file from the top level
+# Load .env file from the top level and get the loaded variables
 env_file_path = File.expand_path("../../.env", __FILE__)
 puts "Loading .env file from: #{env_file_path}"
-load_env(env_file_path)
-puts "FLASK_APP_NAME: #{ENV['FLASK_APP_NAME']}"
-puts "FLASK_ENV: #{ENV['FLASK_ENV']}"
-puts "DOMAIN: #{ENV['DOMAIN']}"
-puts "MARIADB_HOSTNAME: #{ENV['MARIADB_HOSTNAME']}"
-puts "MARIADB_PORT: #{ENV['MARIADB_PORT']}"
-puts "MARIADB_DATABASE: #{ENV['MARIADB_DATABASE']}"
-puts "MARIADB_TEST_DATABASE: #{ENV['MARIADB_TEST_DATABASE']}"
-puts "MARIADB_USER: #{ENV['MARIADB_USER']}"
-puts "MARIADB_PASSWORD: #{ENV['MARIADB_PASSWORD']}"
-puts "MARIADB_ROOT_PASSWORD: #{ENV['MARIADB_ROOT_PASSWORD']}"
-puts "WORKING_DIR: #{ENV['WORKING_DIR']}"
+loaded_env_vars = load_env(env_file_path)
+
+# Print only the variables that were loaded from the .env file
+loaded_env_vars.each do |key, value|
+  puts "#{key}: #{value}"
+end
 
 
 Vagrant.configure("2") do |config|
@@ -65,24 +64,21 @@ Vagrant.configure("2") do |config|
 
   # Load environment variables on vagrant ssh
   config.vm.provision "shell", inline: <<-SHELL
-    echo 'export FLASK_APP_NAME="#{ENV['FLASK_APP_NAME'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export FLASK_ENV="#{ENV['FLASK_ENV'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export DOMAIN="#{ENV['DOMAIN'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_HOSTNAME="#{ENV['MARIADB_HOSTNAME'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_PORT="#{ENV['MARIADB_PORT'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_DATABASE="#{ENV['MARIADB_DATABASE'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_TEST_DATABASE="#{ENV['MARIADB_TEST_DATABASE'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_USER="#{ENV['MARIADB_USER'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_PASSWORD="#{ENV['MARIADB_PASSWORD'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export MARIADB_ROOT_PASSWORD="#{ENV['MARIADB_ROOT_PASSWORD'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    echo 'export WORKING_DIR="#{ENV['WORKING_DIR'].gsub('"', '\"')}"' >> /etc/profile.d/vagrant_env.sh
-    source /etc/profile.d/vagrant_env.sh
+    ENV_FILE="/vagrant/.env"
+    if [ -f $ENV_FILE ]; then
+      export $(cat $ENV_FILE | xargs)
+      while IFS= read -r line; do
+        echo "export $line" >> /etc/profile.d/vagrant_env.sh
+      done < $ENV_FILE
+    else
+      echo "Env file not found: $ENV_FILE"
+      exit 1
+    fi
   SHELL
 
   config.vm.provision "shell", run: "always", inline: <<-SHELL
     echo 'source /etc/profile.d/vagrant_env.sh' >> /home/vagrant/.bashrc
   SHELL
-
 
   # Provider configuration
   config.vm.provider "virtualbox" do |vb|
